name = "CommonSolve"
uuid = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
version = "0.2.6"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]

[compat]
Aqua = "0.8"
ExplicitImports = "1.14.0"
JET = "0.9, 0.10, 0.11"
SafeTestsets = "0.1"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ExplicitImports", "JET", "SafeTestsets", "Test"]
