[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[sources]
CommonSolve = {path = "/home/chrisrackauckas/github-runners/deepsea3-1/_work/CommonSolve.jl/CommonSolve.jl"}

[compat]
CommonSolve = "0.2"
Documenter = "1"
